### ISSUE TITLE
Problem with saving measurement graph on domain-based run

### ISSUE THREAD

**Issue by KourosZanbouri** [wikicensorship/tracevis#68]
Today I tried to run tracevis with a specific target ( with the domain name and "-i" parameter"), and everything went smooth until saving the measurement graph, in which I got a traceback
* data and config measurements were saved successfully

`
Traceback (most recent call last):
  File "./tracevis.py", line 342, in <module>
    main(get_args(sys.argv[1:]))
  File "./tracevis.py", line 335, in main
    if utils.vis.vis(
  File "C:\Users\Kouros\desktop\tracevis\utils\vis.py", line 277, in vis
    dst_addr_id = 'x' + str(int(ipaddress.IPv4Address(dst_addr))) + 'x'
  File "C:\Users\Kouros\AppData\Local\Programs\Python\Python38\lib\ipaddress.py", line 1252, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "C:\Users\Kouros\AppData\Local\Programs\Python\Python38\lib\ipaddress.py", line 1144, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in 'TARGET.DOMAIN.DOMAIN'
`

**Comment by xhdix** [comment]
Thank you for reporting this issue! :heart: :hibiscus: 

`-i` == `--ips` but:
1. There is no timeout in `getaddrinfo()` and there is no easy and cross platform workaround to stop it. So, to make sure that we don't get stuck on `nslookup` we MUST do it manually with scapy. Therefore, we need to work on something like this: https://github.com/wikicensorship/tracevis/blob/63bc2df04c02b6eb489aaaa3e31c8f07ec40e57e/utils/geolocate.py#L15-L31

2. We should stop and show error when the inputs are not IP (for now IPv4, unless we fix #25 )
